version: '2'
services:
  nginx-proxy:
    image: vostro/openresty-proxy
    container_name: openresty-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
